AllCops:
  NewCops: disable
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
# This is causing breaking changes:
Style/ExpandPathArguments:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
